### ISSUE TITLE
chrono's serde feature

### ISSUE THREAD

**Issue by stchris** [museun/whatfeatures#36]
First of all: thanks, I really like using your project!

I'm quite sure this is not a bug in `whatfeatures`, but I'm not entirely sure how this works:

- [chrono's docs](https://docs.rs/chrono/0.4.11/chrono/) say that if you want to use `serde` you need to enable the feature ```chrono = { version = "0.4", features = ["serde"] }```
- I ran `cargo whatfeatures chrono` and I don't see `serde`
- [chrono's Cargo.toml](https://github.com/chronotope/chrono/blob/master/Cargo.toml) mentions the feature

Is this some sort of feature that is not being "exposed" and that's why `whatfeatures` can't pick it up? Or is there something it could do to pick that up? I'd be open to try a PR if you could point me in the right direction.

**Comment by museun** [comment]
Its a known limitation (omission, technically), shortly I'll have a new version which'll handle those cases (and more).

The reason 'serde' doesn't show up is because its an optional dependency and not listed under a `[features]` section. Optional deps can be treated as features, but they aren't explicitly marked as such. [serde is listed as a dep](https://github.com/chronotope/chrono/blob/8060089730a4bbbdb8de3ca25c1d297a374659e6/Cargo.toml#L39)

Right now, the current version uses the crates.io api to get the feature data. Although I can handle the case of optional dependencies using this method, using the http API in this way is discouraged. So I've been (slowly) working on the next version which'll use the 'cargo metadata' aspect of cargo. This'll also allow using this subcommand on local crates.

**Comment by museun** [comment]
I published a new version which redid how it gets the crate information. it should be version `v0.7.1` (`cargo install -f cargo-whatfeatures` to override/update a previous installed one). 

This will be the version that I'd recommend messing around with. The output can be improved a lot, this is just a quick transition from the old style.

I, think, 'optional' features at a top-level should be highlighted as features, but I'm not sure yet.

**Comment by stchris** [comment]
Wow, thanks for the detailed explanation and the quick turnaround. You're awesome! 👍

**Comment by museun** [comment]
Implemented in the 576d74f11d17614cdbf7096bbf110afbadeef9e6
